### ISSUE TITLE
模型文件下载不了

### ISSUE THREAD

**Issue by wanghaoran-ucas** [OpenBGBenchmark/OpenBG-Align#3]
[pytorch_model_8.bin](https://drive.google.com/file/d/1DtYiSQ1fPP1aBGsmIKjz88w1bUcwaTYM/view?usp=sharing)模型文件下载不了，显示被删除了，大佬能重新提供一下链接吗

**Comment by wanghaoran-ucas** [comment]
![b6ebac26116d48827627a8fe8364badbe3c8ad0c](https://user-images.githubusercontent.com/29060320/216800403-2f952b79-06cd-46f4-b7e9-9d4fd53f9767.jpg)

**Comment by zxlzr** [comment]
您好，文件已恢复，非常抱歉给您带来了不便。
